infrastructure:validate:
  stage: validate
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'
  variables:
    ASSET_NAME: infrastructure
  only:
    refs:
      - main
      - develop
    changes:
      - infrastructure/**/*
  before_script:
    - cd ${ASSET_NAME}
  script:
    - terraform init --reconfigure -input=false
    - terraform validate -json

infrastructure:plan:
  stage: plan
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'
  variables:
    ASSET_NAME: infrastructure
    INFR_FILE: vars/infr.tfvars.json
  only:
    refs:
      - main
      - develop
    changes:
      - infrastructure/**/*
  before_script:
    - cd ${ASSET_NAME}
  script:
    - terraform init --reconfigure -input=false
    - terraform plan -input=false -out=plan.tfplan -var-file=${INFR_FILE}
  artifacts:
    paths:
      - ${ASSET_NAME}/plan.tfplan

infrastructure:apply:
  stage: apply
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}'
  when: manual
  variables:
    ASSET_NAME: infrastructure
  only:
    refs:
      - main
    changes:
      - infrastructure/**/*
  before_script:
    - cd ${ASSET_NAME}
  script:
    - terraform init --reconfigure -input=false
    - terraform apply -input=false -auto-approve -compact-warnings plan.tfplan